version: "3.8"

services:
  app:
    build: .
    container_name: builder
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/editor
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: