name: CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend
        run: npm install
        working-directory: ./client

      - name: Build Frontend
        run: npm run build
        working-directory: ./client

      - name: Install Backend
        run: npm install
        working-directory: ./server

      - name: Build Docker Image
        run: docker build -t builder .